### PR TITLE
Scene Slot Increase

### PR DESCRIPTION
**Pull request by Thomas-Smyth**
Increased number of scene slots to 30 from 14.

Changed default scene strings to default PW map.

### CODE REVIEW

**Comment by Thomas-Smyth** [comment]
@WilliamPhoenix reports a bug where when scene 25 is selected, it shows scene 24's name in the server browser.

**Comment by WilliamPhoenix** [comment]
Tested again, putting Rhadaron in slot 30. The server list shows "Blank Scene 29" while the map was actually correctly loaded from slot 30.

**Comment by Thomas-Smyth** [comment]
@WilliamPhoenix bug should be resolved.

**Comment by WilliamPhoenix** [comment]
Tested. Works.

**Pull request merged**
